name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
          distribution: 'adoptopenjdk'
      # Устанавливаем Maven
      - name: Set up Maven 
        id: cache
        uses: actions/cache@v2
        with:
          maven-version: '3.8.4'

      - name: Install dependencies
        run: mvn install  #

      - name: Build Project
        run: mvn clean install 

      - name: Run Unit Tests
        run: mvn test  
